kind: pipeline
type: docker
name: build

steps:
  - name: alpine3.11
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: bogny/tor
      dockerfile: 3.11/Dockerfile
      tags:
        - '3.11'
        - 'latest'
